serial.aio=ch1234g999
serial.gw=gw1234g000

zone.id=Europe/London

ha=192.168.1.18:8123
bearer=eyJhblah iJIUzI1NblahnR5cCI6IkpXVCJ9.eyblahMiOiJkMzU1Y2QxODJlZDE0YWM5Yblahjk2ZGU1Mzc3MmI2YSIsIblahCI6MTc3NjU5Njk2OCwiblahIjoyMDkxOTUblah4fQ.blahKAxa4dgGJv2nIbLvlRu28hVISD_857Aqblah

######################################
#			sensors
######################################

AC_CHARGE_ENERGY_TODAY_KWH=givtcp2_ch1234g999_ac_charge_energy_today_kwh
AC_CHARGE_ENERGY_TOTAL_KWH=givtcp2_ch1234g999_ac_charge_energy_total_kwh
BATTERY_CHARGE_ENERGY_TODAY_KWH=givtcp2_ch1234g999_battery_charge_energy_today_kwh
BATTERY_CHARGE_ENERGY_TOTAL_KWH=givtcp2_ch1234g999_battery_charge_energy_total_kwh
BATTERY_DISCHARGE_ENERGY_TODAY_KWH=givtcp2_ch1234g999_battery_discharge_energy_today_kwh
BATTERY_POWER=givtcp_gw1234g000_battery_power
BATTERY_STACK_1_BMS_TEMPERATURE=givtcp2_battery_stack_1_bms_temperature
BATTERY_THOUGHPUT_TODAY_KWH=givtcp2_ch1234g999_battery_throughput_today_kwh
EPS_POWER=givtcp2_cch1234g999_eps_power
EXPORT_ENERGY_TODAY_KWH=givtcp2_ch1234g999_export_energy_today_kwh
EXPORT_ENERGY_TOTAL_KWH=givtcp2_ch1234g999_export_energy_total_kwh
GRID_VOLTAGE=givtcp2_ch1234g999_grid_voltage
IMPORT_ENERGY_TODAY_KWH=givtcp2_ch1234g999_import_energy_today_kwh
IMPORT_ENERGY_TOTAL_KWH=givtcp2_ch1234g999_import_energy_total_kwh
INVERTER_OUTPUT_FREQUENCY=givtcp2_ch1234g999_inverter_output_frequency
INVERTOR_ENERGY_TOTAL_KWH=givtcp2_ch1234g999_invertor_energy_total_kwh
INVERTOR_POWER=givtcp2_ch1234g999_invertor_power
INVERTOR_TEMPERATURE=givtcp2_ch1234g999_invertor_temperature
LIBERTY_POWER=givtcp_gw1234g000_liberty_power
PV_ENERGY_TODAY_KWH=givtcp2_ch1234g999_pv_energy_today_kwh
PV_ENERGY_TOTAL_KWH=givtcp2_ch1234g999_pv_energy_total_kwh
SOC=givtcp2_ch1234g999_soc

######################################
#			webhooks
######################################


ac.charge.upper.%.limit=target.soc

######################################

ac.charge.1.upper.soc.%.limit=charge.target.soc.1
ac.charge.2.upper.soc.%.limit=charge.target.soc.2
ac.charge.3.upper.soc.%.limit=charge.target.soc.3
ac.charge.4.upper.soc.%.limit=charge.target.soc.4
ac.charge.5.upper.soc.%.limit=charge.target.soc.5
ac.charge.6.upper.soc.%.limit=charge.target.soc.6
ac.charge.7.upper.soc.%.limit=charge.target.soc.7
ac.charge.8.upper.soc.%.limit=charge.target.soc.8
ac.charge.9.upper.soc.%.limit=charge.target.soc.9
ac.charge.10.upper.soc.%.limit=charge.target.soc.10

######################################

ac.charge.1.start.time=charge.start.time.slot.1
ac.charge.2.start.time=charge.start.time.slot.2
ac.charge.3.start.time=charge.start.time.slot.3
ac.charge.4.start.time=charge.start.time.slot.4
ac.charge.5.start.time=charge.start.time.slot.5
ac.charge.6.start.time=charge.start.time.slot.6
ac.charge.7.start.time=charge.start.time.slot.7
ac.charge.8.start.time=charge.start.time.slot.8
ac.charge.9.start.time=charge.start.time.slot.9
ac.charge.10.start.time=charge.start.time.slot.10

######################################

ac.charge.1.end.time=charge.end.time.slot.1
ac.charge.2.end.time=charge.end.time.slot.2
ac.charge.3.end.time=charge.end.time.slot.3
ac.charge.4.end.time=charge.end.time.slot.4
ac.charge.5.end.time=charge.end.time.slot.5
ac.charge.6.end.time=charge.end.time.slot.6
ac.charge.7.end.time=charge.end.time.slot.7
ac.charge.8.end.time=charge.end.time.slot.8
ac.charge.9.end.time=charge.end.time.slot.9
ac.charge.10.end.time=charge.end.time.slot.10

######################################

dc.discharge.1.lower.soc.%.limit=discharge.target.soc.1
dc.discharge.2.lower.soc.%.limit=discharge.target.soc.2
dc.discharge.3.lower.soc.%.limit=discharge.target.soc.3
dc.discharge.4.lower.soc.%.limit=discharge.target.soc.4
dc.discharge.5.lower.soc.%.limit=discharge.target.soc.5
dc.discharge.6.lower.soc.%.limit=discharge.target.soc.6
dc.discharge.7.lower.soc.%.limit=discharge.target.soc.7
dc.discharge.8.lower.soc.%.limit=discharge.target.soc.8
dc.discharge.9.lower.soc.%.limit=discharge.target.soc.9
dc.discharge.10.lower.soc.%.limit=discharge.target.soc.10

######################################

dc.discharge.1.start.time=discharge.start.time.slot.1
dc.discharge.2.start.time=discharge.start.time.slot.2
dc.discharge.3.start.time=discharge.start.time.slot.3
dc.discharge.4.start.time=discharge.start.time.slot.4
dc.discharge.5.start.time=discharge.start.time.slot.5
dc.discharge.6.start.time=discharge.start.time.slot.6
dc.discharge.7.start.time=discharge.start.time.slot.7
dc.discharge.8.start.time=discharge.start.time.slot.8
dc.discharge.9.start.time=discharge.start.time.slot.9
dc.discharge.10.start.time=discharge.start.time.slot.10

######################################

dc.discharge.1.end.time=discharge.end.time.slot.1
dc.discharge.2.end.time=discharge.end.time.slot.2
dc.discharge.3.end.time=discharge.end.time.slot.3
dc.discharge.4.end.time=discharge.end.time.slot.4
dc.discharge.5.end.time=discharge.end.time.slot.5
dc.discharge.6.end.time=discharge.end.time.slot.6
dc.discharge.7.end.time=discharge.end.time.slot.7
dc.discharge.8.end.time=discharge.end.time.slot.8
dc.discharge.9.end.time=discharge.end.time.slot.9
dc.discharge.10.end.time=discharge.end.time.slot.10


######################################

# AC Charge Enable
# Register Name: Enable AC Charge Upper % Limit true

ac.charge.enable=ac.charge.enable.on

######################################

# AC Charge Enable
# Register Name: Enable AC Charge Upper % Limit false

ac.charge.disable=ac.charge.enable.off

######################################

# Enable DC Discharge

enable.dc.discharge=enable.dc.discharge


######################################

# Battery Pause Mode

battery.pause.mode=battery.pause.mode

######################################

# Battery Charge Rate

battery.charge.rate=battery.charge.rate

######################################

# Battery Discharge Rate

battery.discharge.rate=battery.discharge.rate

######################################

# Enable Charge Target

enable.charge.target=enable.charge.target

######################################

# Disable Charge Target

disable.charge.target=disable.charge.target

######################################
smart-device=insert_api_token_here
#
inverter=insert_api_token_here
#
# Example: 5.6kWp PV panels @ 34 degrees tilt 12 degrees west of south (max generation around 40 mins after solar noon)
#
forecast.solar=https://api.forecast.solar/estimate/watthours/day/my_latitude/my_longitude/34/12/5.6
forecast.max.age.seconds=21600
#
# Example: find sunrise solar noon and sunset times for specified location with results in specified json file
#
sunrise.sunset.api=https://api.sunrisesunset.io/json?lat=my_latitude&lng=my_longitude&timezone=UTC&&time_format=24
sunrise.sunset.file=sunrise.sunset.json
#
#
# list any smart device alias and ids 
PlugA=08f6b4f9-0000-4d41-0000-95214d78e740
PlugB=aba03ce8-0000-41f9-0000-91876bb0cd45
PlugC=bb1c988e-0000-4ad5-0000-53c5a99f5841
PlugD=76412d97-0000-4ac0-0000-238ed1e1a6e2
PlugE=9cc9b483-0000-44ff-0000-1c47395fbc67
PlugF=f1d45611-0000-4ee3-0000-1ce2d7757f39
PlugG=74726c82-0000-4ad6-0000-6984effe4f25
PlugH=aa52fd1c-0000-4341-0000-cf7bd21f8e42
PlugI=6eec8466-0000-408f-0000-8ddf898f6fa2
PlugJ=cda12770-0000-4119-0000-1410c9adc54a

# This version
version=${project.version}
